### ISSUE TITLE
Feature: Function should support multipart/form-data and application/x-www-form-urlencoded content type

### ISSUE THREAD

**Issue by thesayyn** [spica-engine/spica#28]
Currently, functions support "application/bson" and "application/json" payloads however it must handle other most commonly used content types like 

- application/x-www-form-urlencoded
- multipart/form-data

So function developers won’t have to handle them for each function.

**Comment by TolgaYigit** [comment]
@thesayyn Is this issue still valid?

**Comment by thesayyn** [comment]
Yes, this is still relevant.

**Comment by thesayyn** [comment]
even though it is not so important.
