### ISSUE TITLE
dead link, dead cert

### ISSUE THREAD

**Issue by peterennis** [spica-engine/spica#48]
![Capture400](https://user-images.githubusercontent.com/140737/62984151-f1e5ae80-bde6-11e9-96a7-f5b6ae9eb88d.png)
![Capture399](https://user-images.githubusercontent.com/140737/62984152-f1e5ae80-bde6-11e9-9823-13e9ed15f286.png)

**Comment by thesayyn** [comment]
Hello there thank you for this issue.

Actually, we are still in pre-release stage so our site isn't available at this moment 😊

Also, if you are curious about our site you can check it out on next.spicaengine.com

The second picture belongs to my personal website which is out of scope of this project.
