### ISSUE TITLE
There is a problem with the links.

### ISSUE THREAD

**Issue by caglarkarakoc** [spica-engine/spica#79]
- https://spicaengine.com/
Your connection is not private. 

- readme.md file:
 **Getting Started guide** link does not work
 https://next.spicaengine.com/docs/guide/getting-started

**Comment by thesayyn** [comment]
Thank you for reporting this. We are still working on some improvements on the site and the documentation. soon we will fix these issues. 😊

**Comment by TolgaYigit** [comment]
Links on the readme file are fixed with pr number #76 and it's merged to master. 
@tthiscafer is working on the SSL certificate on the landing page.

**Comment by thesayyn** [comment]
Seems like the SSL issue is solved.
