### ISSUE TITLE
spica bucket orm error

### ISSUE THREAD

**Issue by wschmid4711234** [spica-engine/spica#814]
Hi everyone

I have installed spica, according to [here](https://spicaengine.com/docs/start/installation), and started a project instance.

I have created a bucket and an API-key.

![image](https://user-images.githubusercontent.com/98827440/152347861-9c311e14-7aaa-4c55-bd4e-2efbb993d554.png)

It's running:

qqqqqqqq@spicadev:~/spicaclient01$ netstat -tuanp|grep 4500
(Es konnten nicht alle Prozesse identifiziert werden; Informationen über
nicht-eigene Processe werden nicht angezeigt; Root kann sie anzeigen.)
tcp        0      0 0.0.0.0:4500            0.0.0.0:*               LISTEN      -                   
tcp6       0      0 :::4500                 :::*                    LISTEN      - 

Spica client version:

qqqqqqqq@spicadev:~/spicaclient01$ cat package.json 
{
  "dependencies": {
    "@spica/cli": "^0.9.15"
  }
}

Now I'm trying to generate the ORM file, but it fails. I have tried different systems (local and remote) and different ways of assigning parameters (with / without "=" sign).

qqqqqqqq@spicadev:~/spicaclient01$ spica bucket orm --url=http://localhost:4500 --apikey=405gzo18kz5q4ykk
✖ Building interface and method definitions..
Cannot create property 'title' on string '!'
TypeError: Cannot create property 'title' on string '!'
    at makeTitlesUnique (/usr/local/lib/node_modules/@spica/cli/src/commands/bucket/orm.js:249:26)
    at Object.createFileContent (/usr/local/lib/node_modules/@spica/cli/src/commands/bucket/orm.js:65:19)
    at Object.op (/usr/local/lib/node_modules/@spica/cli/src/commands/bucket/orm.js:25:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Se.orm [as _action] (/usr/local/lib/node_modules/@spica/cli/src/commands/bucket/orm.js:13:5)
    at async Se.run (/usr/local/lib/node_modules/@spica/cli/node_modules/@caporal/core/dist/index.js:1:27579)
    at async Te._run (/usr/local/lib/node_modules/@spica/cli/node_modules/@caporal/core/dist/index.js:1:32257)

What can I do?

I have also tried other spical client commands, and they seem to work fine.

Like this one:

qqqqqqqq@spicadev:~/spicaclient01$ spica project ls
NAMESPACE         AGE                       STATUS            VERSION       PORT               DESCRIPTION
testspica01       52y 45d 14h 54m 17s       Up 22 hours       latest        0.0.0.0:4500

**Comment by htuna07** [comment]
Hi @wschmid4711234 . Thanks for your contribution. The **--url** parameter value is actually where the spica **api** is serving. It seems the `http://localhost:4500` is where the spica **client** is serving. You should use `http://localhost:4500/api` instead. Try to run this command,
`spica bucket orm --url=http://localhost:4500/api --apikey=405gzo18kz5q4ykk`

**Comment by wschmid4711234** [comment]
Ah, great, thank you, I'll try that!

**Comment by wschmid4711234** [comment]
Well - I get this now (wrapped in a lengthy json object):

```
    data: {
      statusCode: 403,
      message: 'You do not have sufficient permissions to do bucket:index on resource ',
      error: 'Forbidden'
    }
```
I'm not aware of any problems with permissions - it doesn't say anywhere that permissions need to be adapted, and they seem fully permissive to me.

Maybe you want to consider changing the [doc site](https://spicaengine.com/docs/concept/bucket), if I remember correctly, it didn't mention the "api" part at the end. Btw., the doc site gives a lot of errors today and doesn't show the text.

Lots of stuff like this:

`POST https://mc.yandex.com/clmap/56919037?page-url=https%3A%2F%2Fspicaengine.com%2Fdocs%2Fstart%2Fgetting-started&pointer-click=rn%3A475594143%3Ax%3A14256%3Ay%3A35576%3At%3A2687%3Ap%3AA%3BA*2A****%3AX%3A375%3AY%3A395&browser-info=gdpr%3A14%3Au%3A1643991094210559708%3Av%3A741%3Avf%3A7oivoclvcqev9drxhj3%3Arqnl%3A1%3Ast%3A1643991363&t=gdpr(14)ti(0)&force-urlencoded=1 504 (Gateway Timeout)`

**Comment by htuna07** [comment]
You need to attach the relevant policy to your API key to run that command with no error. Bucket read-only access will be enough for your case. Check the passport section of the documentation for more info.

And you're right, we should consider adding these details to the documentation to make people run this command with no issue. 

Lastly, I'll check the documentation site errors and fix them as soon as possible.

**Comment by htuna07** [comment]
Is there any other issue with that command? I hope you ran this command with success and you are ready to use that file in your projects @wschmid4711234.
